language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
# Follow the work-around proposed in https://github.com/travis-ci/travis-ci/issues/9815 to enable Python 3.7 on Travis.
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
install:
  - pip install -r requirements.txt
  - pip install .
script: python tests/pytrec_eval_tests.py